Error catching in the case where Argonaut does not install

diff --git a/squeeze-install-FusionDirectory-Argonaut b/squeeze-install-FusionDirectory-Argonaut
--- a/squeeze-install-FusionDirectory-Argonaut
+++ b/squeeze-install-FusionDirectory-Argonaut
@@ -28,7 +28,12 @@ fi
 # NOTE:: We install argonaut-client as well as the server because both 
 # Fusion Directory and the infrastructure we're controlling are on the one box.
 
-apt-get -y --allow-unauthenticated install argonaut-client-management argonaut-server argonaut-common 
+if apt-get -y --allow-unauthenticated install argonaut-client-management argonaut-server argonaut-common; then
+	echo "Installation of Argonaut and prerequisite packages successful..."
+else
+	echo "Installation of Argonaut and prerequisite packages failed.  Exiting..."
+	exit 1
+fi 
 
 # Argonaut needs to be configured. :
 
