Update script...  (incomplete)

diff --git a/squeeze-install-FusionDirectory-plugin-OPSI b/squeeze-install-FusionDirectory-plugin-OPSI
--- a/squeeze-install-FusionDirectory-plugin-OPSI
+++ b/squeeze-install-FusionDirectory-plugin-OPSI
@@ -17,10 +17,10 @@ if [ ! -f /etc/gosa/gosa.conf ]; then
   echo "installed and configured before we can continue..."
   exit 1
 fi
-# squeeze-install-FusionDirectory-Server-Infrastructure
+# squeeze-install-FusionDirectory-Argonaut
 if [ ! -f /etc/gosa-si/server.conf ]; then
-  echo "Run the squeeze-install-FusionDirectory-Server-Infrastructure script before"
-  echo "this one.  GOsa-SI must be installed and configured before we can continue."
+  echo "Run the squeeze-install-FusionDirectory-Argonaut script before this"
+  echo "one.  GOsa-SI must be installed and configured before we can continue."
   exit 1
 fi
 # squeeze-install-FusionDirectory-plugin-DHCP
@@ -43,8 +43,8 @@ fi
 #  echo "must be installed and configured before we can continue..."
 #  exit 1
 #fi
-# squeeze-install-FusionDirectory-Samba+goPDC
 
+# squeeze-install-FusionDirectory-Samba+goPDC
 if [ ! -f /etc/samba/smb.conf ]; then
   echo "Run the squeeze-install-FusionDirectory-Samba+goPDC script before this one. Samba"
   echo "must be installed and configured before we can continue..."
@@ -80,17 +80,27 @@ fi
 #	exit 1
 #fi
 
-grep -q "http://download.uib.de/debian" /etc/apt/sources.list
+# Add the Squeeze OPSI repo
+grep -q "http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/Debian_6.0 ./" /etc/apt/sources.list
 if [ "$?" != 0 ]; then
-        echo "deb http://download.uib.de/debian lenny opsi3.4" >> /etc/apt/sources.list
+        echo "http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/Debian_6.0 ./" >> /etc/apt/sources.list
 fi
 
-apt-get update
-apt-get install -y wget lsof host python-mechanize p7zip-full cabextract atftpd
-apt-get install -y smbclient smbfs
-apt-get install -y openjdk-6-jre
+# Add key for Squeeze OPSI repo
+wget -O - http://download.opensuse.org/repositories/home:/uibmz:/opsi:/opsi40/Debian_6.0/Release.key | apt-key add -
 
-# Make sure the Sun OpenJDK JRE is used.  Use --config instead of --set to
+apt-get update
+apt-get install -y wget lsof host python-mechanize p7zip-full cabextract atftpd openbsd-inetd
+apt-get install -y smbclient smbfs
+
+# FIXME: Hopefully the OpenJDK works...  if not revert to the non-free Sun JDK
+if apt-get install -y openjdk-6-jre; then
+else
+  echo "Didn't successfully install "
+  exit 1
+fi
+
+# Make sure the OpenJDK JRE is used.  Use --config instead of --set to
 # make this change interactively if required.
 update-alternatives --set java /usr/lib/jvm/java-6-openjdk/jre/bin/java
 
@@ -124,19 +134,14 @@ update-alternatives --set java /usr/lib/jvm/java-6-openjdk/jre/bin/java
 
 
 
-# This Gosa SI package needs to be installed... 
-if apt-get -y --allow-unauthenticated install gosa-si-server-opsi; then
-  echo "Installed GOsa Server Infrastructure OPSI module from repository..."
+# This Argonaut package needs to be installed... 
+if apt-get -y --allow-unauthenticated install fusiondirectory-plugin-opsi argonaut-fuse-opsi; then
+  echo "Installed Argonaut and FD OPSI modules from repository..."
 else
-  echo "Can't find GOsa Server Infrastructure OPSI module in the repository..."
-  # At the moment of writing amd64 gosa-si debs aren't available
-  echo "Downloading, compiling and installing gosa-si-server-opsi from source..."
-  cd /usr/src
-  svn co https://oss.gonicus.de/repositories/gosa/trunk/gosa-si gosa-si
-  cd /usr/src/gosa-si
-  dpkg-buildpackage -b
-  cd /usr/src
-  dpkg -i gosa-si-server-opsi_2.6*.deb
+  echo "Can't find Argonaut/FusionDirectory OPSI module/s in the repository/s..."
+  # At the moment of writing up-to-date debs aren't available
+  echo "Use the argonaut_nightly.sh build script to make it..."
+  exit 1
 fi
 
 # OPSI administrators must belong to the group "opsiadmin" and
@@ -182,18 +187,14 @@ read dummyvar
 
 # Unfortunately the Samba docs say it's no longer possible for Samba to support
 # multiple password backends, so I can't simply have a local password.
+ 
+OPSIADMIN_PW="aicham"
+sed -i 's@^admin=@admin=opsiadmin@' /etc/argonaut/argonaut-fuse.conf
+# Only replace the SECOND occurrence of "password=" in the config, because the first is for FAI
+sed -i '/^password=/{:1 n;/^password=/{s/^password=[\t]*$/password='$OPSIADMIN_PW'/;:2 n;$!b2};b1}' /etc/argonaut/argonaut-fuse.conf
+sed -i 's@^server=@server='`hostname --fqdn`'@' /etc/argonaut/argonaut-fuse.conf
+sed -i 's@^lang=@lang=en@' /etc/argonaut/argonaut-fuse.conf
 
-# When starting gosa-si I get WARNING: opsi-module is installed
-# but not enabled in config file, please set under section '[OPSI]':
-# 'enabled = true'.  I changed /etc/gosa-si/server.conf and this seemed
-# to fix this error.  
-cat >> /etc/gosa-si/server.conf <<-EOF
-
-	[OPSI]
-	enabled = true
-	admin = opsiadmin
-	password = $OPSIADMIN_PW
-EOF
 # Check cfg_defaults in the /usr/sbin/gosa-si-server script to get an idea of
 # other configuration options available in server.conf. This is not documented.
 
@@ -205,31 +206,9 @@ EOF
 #printf "%s\n" '/\[ArpHandler\]/' '/enabled = false/s/false/true' w | ex -s /etc/gosa-si/server.conf
 
 apt-get -qq install libproc-daemon-perl syslinux
+# FIXME: Does this need to happen (ie. is tftpd accidentally installed)
 apt-get remove tftpd
 update-inetd --remove tftpd
-
-if apt-get -y --allow-unauthenticated install fts fts-opsi; then
-  echo "Installed fts from repositories..."
-else
-  # tftpd-hpa is installed by default with FAI, but we are using Fusion Directory,
-  # and we therefore we must remove this package and use fts+atftpd instead.
-  apt-get -qq purge tftpd-hpa
-  cd /usr/src
-  svn co https://oss.gonicus.de/repositories/goto/trunk/fts fts
-  cd /usr/src/fts
-  dpkg-buildpackage -b
-  cd /usr/src
-  dpkg -i fts_*.deb
-  dpkg -i fts-opsi_*.deb
-fi
-
-# Edit [OPSI] section and [LDAP] sections in /etc/fts/fts.conf
-# to be correct for our local scenario.
-sed -i 's@#\[OPSI\]@\[OPSI\]@' /etc/fts/fts.conf
-sed -i 's@#admin = cajus@admin = opsiadmin@' /etc/fts/fts.conf
-sed -i 's@#password = tester@password = '$OPSIADMIN_PW'@' /etc/fts/fts.conf
-sed -i 's@#server = dyn-muc-02.intranet.gonicus.de@server = '$my_fqdn'@' /etc/fts/fts.conf
-sed -i 's@#lang = de@lang = en@' /etc/fts/fts.conf
 
 # We get our admin dn and password from fusiondirectory.conf as these are required in the
 # [LDAP] section - fts must use them to connect to our LDAP directory.
@@ -237,8 +216,9 @@ LDAP_ADMIN_DN=`grep 'adminDn="' /etc/fusiondirectory/fusiondirectory.conf | awk 
 echo "LDAP admin dn extracted from /etc/fusiondirectory/fusiondirectory.conf"
 LDAP_ADMIN_PW=`grep 'adminPassword="' /etc/fusiondirectory/fusiondirectory.conf | awk -F'"' '{print $2 }'`
 echo "LDAP admin password extracted from /etc/fusiondirectory/fusiondirectory.conf"
-sed -i 's@#auth_dn=@auth_dn='$LDAP_ADMIN_DN'@' /etc/fts/fts.conf
-sed -i 's@#auth_pwd=@auth_pwd='$LDAP_ADMIN_PW'@' /etc/fts/fts.conf
+# ...then configure our Argonaut-fuse server to bind to LDAP as admin.
+sed -i 's@^dn=[\t]*$@dn='$LDAP_ADMIN_DN'@' /etc/argonaut/argonaut-fuse.conf
+sed -i '0,/password/s@^password[\t]*$=@password='$LDAP_ADMIN_PW'@' /etc/argonaut/argonaut-fuse.conf
 
 ## These packages are replaced by fts and opsi-depot-support in Fusion Directory, and
 ## I've made a note here in case anyone was wondering about it :
